# services:
#     # Remarks (image):
#     # 1.  Dockerfile command will execute once only when container is created, think of it as initialization
#     # image: mcr.microsoft.com/mssql/server:latest
#     # Remarks (volumes):
#     # 1.  Not currently support mapping the complete /var/opt/mssql directory. However, you can map a subdirectory, 
#     #     such as /var/opt/mssql/data to your host machine.
#     #     Reference:
#     #       https://stackoverflow.com/questions/65307784/mssql-container-fails-to-start-when-mapping-volumes-after-upgrading-to-wsl2
#     # 2.  For windows, "~" refers to C:\Users\<username>
#     # 3.  docker-compose volumes command will overwrite the command of COPY in Dockerfile (Image)
#     # 4.  Possible to add multiple mapping, for example:
#     #        volumes:
#     #          - ~/tomcat/deploy:/usr/local/tomcat/webapps
#     #          - ~/tomcat/log:/usr/local/tomcat/log
# https://container-registry.oracle.com/ords/f?p=113:10:2828295998744:::::

version: '3.1'

services:
  oracle-db:
    image: container-registry.oracle.com/database/enterprise:21.3.0.0
    container_name: oracle_db_21.3.0
    environment:
      ORACLE_SID: ORCL
      ORACLE_PWD: demo1234
      INIT_SGA_SIZE: 2048
      INIT_PGA_SIZE: 1024
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - ~/oracle-data:/opt/oracle/oradata
      - ./script/database:/docker-entrypoint-initdb.d
    restart: always
