version: '3.1'

services:
  oracle-db:
    image: container-registry.oracle.com/database/enterprise:21.3.0.0
    container_name: oracle_db_21.3.0
    environment:
      ORACLE_SID: ORCL
      ORACLE_PWD: demo1234
      INIT_SGA_SIZE: 2048
      INIT_PGA_SIZE: 1024
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      # For windows, "~" refers to C:\Users\<username>
      - ~/oracle-data:/opt/oracle/oradata 
      - ./script/database:/docker-entrypoint-initdb.d
    restart: always
    # healthcheck:
    #   test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus system/demo1234@localhost:1521/ORCL || exit 1"]
    #   interval: 2m  # How often to perform the check
    #   timeout: 30s  # Maximum time to wait for a successful check
    #   retries: 3  # Number of retries before marking the container as unhealthy
