from enum import Enum

class DiscordChannel(str, Enum):
    INITIAL_POP = 'INITIAL_POP'
    INITIAL_DIP = 'INITIAL_DIP'
    TOP_GAINER_SCANNER_LIST = 'TOP_GAINER_SCANNER_LIST'
    TOP_LOSER_SCANNER_LIST = 'TOP_LOSER_SCANNER_LIST'
    YESTERDAY_TOP_GAINER_SCANNER_LIST = 'YESTERDAY_TOP_GAINER_SCANNER_LIST'
    TEXT_TO_SPEECH = 'TEXT_TO_SPEECH'
    CHATBOT_LOG = 'CHATBOT_LOG'
    CHATBOT_ERROR_LOG = 'CHATBOT_ERROR_LOG'
    DEVELOPMENT_TEST = 'DEVELOPMENT_TEST'