from enum import Enum

class DiscordMessageChannel(str, Enum):
    # Primary
    TEXT_TO_SPEECH = 'TEXT_TO_SPEECH' 
    CHATBOT_ERROR_LOG = 'CHATBOT_ERROR_LOG'
    # Screnner
    SMALL_CAP_TOP_GAINER_SCREENER_LIST = 'SMALL_CAP_TOP_GAINER_SCREENER_LIST' 
    YESTERDAY_TOP_GAINER_SCREENER_LIST = 'YESTERDAY_TOP_GAINER_SCREENER_LIST'
    # Scanner
    SMALL_CAP_INITIAL_POP = 'SMALL_CAP_INITIAL_POP '
    YESTERDAY_TOP_GAINER_BULLISH_DAILY_CANDLE = 'YESTERDAY_TOP_GAINER_BULLISH_DAILY_CANDLE' 
    SMALL_CAP_INTRA_DAY_BREAKOUT = 'SMALL_CAP_INTRA_DAY_BREAKOUT '
    IPO_LIST = 'IPO_LIST'
    FOREX = 'FOREX'
    # Log
    YESTERDAY_TOP_GAINER_SCRAPER_HISTORY_LOG = 'YESTERDAY_TOP_GAINER_SCRAPER_HISTORY_LOG'
    SERP_API_ACCOUNT_INFO_LOG = 'SERP_API_ACCOUNT_INFO_LOG'
    SERP_API_SEARCH_QUERY_LOG = 'SERP_API_SEARCH_QUERY_LOG'
    SERP_API_SEARCH_RESULT_LOG = 'SERP_API_SEARCH_RESULT_LOG'