CREATE USER C##demo IDENTIFIED BY demo
DEFAULT TABLESPACE USERS;

GRANT DBA TO C##demo;



--------------------------------------------------------
--  DDL for Table PATTERN_ANALYSIS
--------------------------------------------------------

  CREATE TABLE "PATTERN_ANALYSIS" 
   (	"TICKER" VARCHAR2(4 BYTE), 
	"HIT_SCANNER_DATETIME" TIMESTAMP (6), 
	"SCAN_PATTERN" VARCHAR2(50 BYTE), 
	"BAR_SIZE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PATTERN_ANALYSIS
--------------------------------------------------------

  ALTER TABLE "PATTERN_ANALYSIS" MODIFY ("TICKER" NOT NULL ENABLE);
  ALTER TABLE "PATTERN_ANALYSIS" MODIFY ("HIT_SCANNER_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "PATTERN_ANALYSIS" MODIFY ("SCAN_PATTERN" NOT NULL ENABLE);
  ALTER TABLE "PATTERN_ANALYSIS" MODIFY ("BAR_SIZE" NOT NULL ENABLE);



--------------------------------------------------------
--  DDL for Table TOP_GAINER_HISTORY
--------------------------------------------------------

  CREATE TABLE "TOP_GAINER_HISTORY" 
   (	"TICKER" VARCHAR2(4 BYTE), 
	"COMPANY" VARCHAR2(200 BYTE), 
	"SECTOR" VARCHAR2(100 BYTE), 
	"INDUSTRY" VARCHAR2(100 BYTE), 
	"SCAN_DATE" TIMESTAMP (6), 
	"PRICE" FLOAT(126), 
	"VOLUME" NUMBER, 
	"PERCENTAGE" FLOAT(126), 
	"MARKET_CAP" NUMBER, 
	"COUNTRY" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TOP_GAINER_HISTORY
--------------------------------------------------------

  ALTER TABLE "TOP_GAINER_HISTORY" MODIFY ("TICKER" NOT NULL ENABLE);
  ALTER TABLE "TOP_GAINER_HISTORY" MODIFY ("COMPANY" NOT NULL ENABLE);
  ALTER TABLE "TOP_GAINER_HISTORY" MODIFY ("SCAN_DATE" NOT NULL ENABLE);
  ALTER TABLE "TOP_GAINER_HISTORY" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "TOP_GAINER_HISTORY" MODIFY ("VOLUME" NOT NULL ENABLE);
  ALTER TABLE "TOP_GAINER_HISTORY" MODIFY ("PERCENTAGE" NOT NULL ENABLE);



--------------------------------------------------------
--  DDL for Table IPO_LIST
--------------------------------------------------------
CREATE TABLE "IPO_LIST" 
(
    "TICKER" VARCHAR2(4 BYTE) NOT NULL,
    "COMPANY_NAME" VARCHAR2(200 BYTE) NOT NULL,
    "OFFERING_PRICE" NUMBER(6, 2),
    "OFFERING_SHARES" NUMBER(20),
    "OFFERING_AMOUNT" NUMBER(20, 2),
    "IPO_DATETIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
    "OFFICAL_WEBSITE" VARCHAR2(500 BYTE),
    "ADDRESS" VARCHAR2(200 BYTE) NOT NULL,
    "NUMBER_OF_EMPLOYEE" VARCHAR2(20 BYTE)
) SEGMENT CREATION DEFERRED 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
TABLESPACE "USERS";
